PROGRAM CREATE_SURFACE
    
    USE MODULE_CREATE_SURFACE
    
    TYPE(CONFIG) :: C
    TYPE(SURFACE) :: S
    
    OPEN(UNIT=21,FILE='log.txt', STATUS='REPLACE')
    CLOSE(21)
    
    
    CALL SET_CONFIG(C)
    CALL DEF_SURFACE(C, S)
    CALL WRITE_VTK(S)
    
END PROGRAM